import type { Application } from 'egg';

export default (app: Application) => {
  const { router, controller } = app;
  router.get('/internal/health', controller.platform.health);
  router.post('/internal/ai-runtime-events', controller.platform.runtimeEvent);
  router.post('/webhooks/stripe', controller.platform.stripeWebhook);
  router.post('/api/activation/exchange', controller.platform.exchangeActivationTicket);
  router.post('/api/auth/register', controller.platform.registerWithEmail);
  router.post('/api/auth/login', controller.platform.loginWithEmail);
  router.get('/api/auth/me', controller.platform.me);
  router.post('/api/auth/password', controller.platform.setPassword);
  router.post('/api/workflow-runs', controller.platform.createRun);
  router.post('/api/billing/checkout-session', controller.platform.createStripeCheckout);
  router.post('/api/workflow-templates/:templateId/publish', controller.platform.publishTemplate);
  router.get('/api/pipeline-templates', controller.platform.pipelineTemplates);
  router.get('/api/pipelines', controller.platform.pipelines);
  router.post('/api/pipelines', controller.platform.createPipeline);
  router.patch('/api/pipelines/:pipelineId', controller.platform.updatePipeline);
  router.post('/api/pipelines/:pipelineId/test', controller.platform.testPipeline);
  router.post('/api/pipelines/:pipelineId/activate', controller.platform.activatePipeline);
  router.get('/api/zernio/connect', controller.platform.connectZernio);
  router.get('/api/zernio/callback', controller.platform.zernioCallback);
  router.post('/api/zernio/select', controller.platform.selectZernio);
  router.post('/api/zernio/sync', controller.platform.syncZernio);
  router.get('/api/zernio/accounts', controller.platform.connectedAccounts);
  router.get('/api/approval-requests', controller.platform.approvals);
  router.get('/api/runs/:runId', controller.platform.run);
  router.post('/api/approval-requests/:approvalId/:decision', controller.platform.decideApproval);
  router.get('/api/billing/task-events', controller.platform.taskEvents);
  router.get('/api/billing/usage', controller.platform.billingUsage);
  router.post('/api/referral/link', controller.platform.referralLink);
  router.get('/api/referral/summary', controller.platform.referralSummary);
  router.post('/api/billing/entitlements', controller.platform.updateBillingEntitlements);
  router.get('/api/admin/workspaces', controller.platform.adminWorkspaces);
  router.post('/api/admin/workspaces/:workspaceId/entitlements', controller.platform.adminUpdateEntitlements);
  router.get('/api/admin/feedback', controller.platform.adminFeedback);
  router.patch('/api/admin/feedback/:ticketNo', controller.platform.adminUpdateFeedback);
  router.get('/api/admin/jobs', controller.platform.adminJobs);
  router.post('/api/admin/jobs/:jobId/replay', controller.platform.adminReplayJob);
  router.get('/api/admin/referrals', controller.platform.adminReferrals);
  router.post('/api/admin/referrals/:ledgerId/void', controller.platform.adminVoidReferral);
  router.post('/api/feedback', controller.platform.feedback);
  router.get('/api/audit-events', controller.platform.auditEvents);
};
